# SYNOPSIS
#
#   AC_PKG_WXWIDGETS
#
# DESCRIPTION
#
#   This macro defines external libraries configuration.

echo "WWWWWWWWWWWW"
AC_DEFUN([AC_PKG_WXWIDGETS],[
	UDF_LOCAL_CPPFLAGS="\
		-L$WXDIR/include"

	UDF_LOCAL_LDFLAGS="\
		-L$WXDIR/lib -lwx*.a"

	#export UDF_WITH_CPPFLAGS="$UDF_LOCAL_CPPFLAGS $UDF_WITH_CPPFLAGS"
	#export UDF_WITH_LDFLAGS="$UDF_LOCAL_LDFLAGS $UDF_WITH_LDFLAGS"
])

