#! /bin/bash

#git clean -d -f -q -e version.num

if [ ! -d build ]; then
	mkdir build
fi

./autogen.sh

cd build 

if [[ $@ == **rf** ]]; then
    	echo "Clean build directory..."
	rm -rf *
fi

if [[ $@ == **c** ]]; then
    	echo "Reconfigure build..."
	../configure
fi

make
cd ..
