/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:
 * Created:
 * Copyright:
 * License:   	wxWidgets license (www.wxwidgets.org)
 *
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

#include "cdbmanager.h"
#include "dbutils.h"
#include "udfexceptions.h"

#include "udfSettings.h"
#include "udfLoginDlg.h"
#include "locale.h"
// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	bool res = false;
	
	SetVendorName(wxT("andrian yablonskyy"));
    SetAppName(wxT("udf"));
	
	setlocale(LC_ALL, "Ukraine");
	try
	{
		do
		{
			CDbManager* pDbMgr = NULL;
			do
			{
				pDbMgr = CDbManager::Instance();
				// Connection OK
				if(pDbMgr->IsOk())
				{
					break;
				}
				
				//Cancel pressed
				if(wxID_OK != udfSettings(NULL).ShowModal())
				{
					break;
				}
			}
			while(1);
			
			if(!pDbMgr->IsOk())
			{
				break;
			}
			
			if(wxID_OK != udfLoginDlg(NULL).ShowModal())
			{
				break;
			}

			SetTopWindow( new udfMainFrameBase( NULL ) );
			GetTopWindow()->Show();
			res = true;
		}while(0);
	}
	catch(...)
	{
		ShowWarning(_("Unhandled error has been happened. Program will be closed."));
	}

	// true = enter the main loop
	return res;
}
