#ifndef __udfAccountInfo__
#define __udfAccountInfo__

/**
@file
Subclass of AccountInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing AccountInfo */
class udfAccountInfo : public AccountInfo
{
protected:
	// Handlers for AccountInfo events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfAccountInfo( wxWindow* parent );
};

#endif // __udfAccountInfo__
