#ifndef __udfBlockInfo__
#define __udfBlockInfo__

/**
@file
Subclass of BlockInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

class udfMainFrameBase;

/** Implementing BlockInfo */
class udfBlockInfo : public BlockInfo
{
protected:
	// Handlers for BlockInfo events.
	void OnUpdateBlock( wxCommandEvent& event );
	void OnBlockCategories( wxCommandEvent& event );
	void OnCellChange( wxGridEvent& event );
	void OnCellLeftClick( wxGridEvent& event );
	void OnSelectCell( wxGridEvent& event );
public:
	/** Constructor */
	udfBlockInfo( wxWindow* parent);
//// end generated class members

private:
	CDbConnection*			m_pCon;
	udfMainFrameBase*		m_pMainWindow;
	wxTreeCtrl*				m_pTree;
	wxTreeItemId*			m_pParentItem;
	wxTreeItemId*			m_pTreeItemId;
	
public:
	bool			Show(bool show = true);
	void			SetMainWindow(udfMainFrameBase* pMain) {m_pMainWindow = pMain;};
	void			SetCsTreeItem(wxTreeCtrl* pTree, wxTreeItemId* pParentItem, wxTreeItemId* pItemId) {m_pTree = pTree; m_pParentItem = pParentItem; m_pTreeItemId = pItemId;};
};

#endif // __udfBlockInfo__
