#ifndef __udfChampionshipCategoriesMngrDlg__
#define __udfChampionshipCategoriesMngrDlg__

/**
@file
Subclass of ChampionshipCategoriesMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing ChampionshipCategoriesMngrDlg */
class udfChampionshipCategoriesMngrDlg : public ChampionshipCategoriesMngrDlg
{
protected:
	// Handlers for ChampionshipCategoriesMngrDlg events.
	void OnAddAll( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnRemoveAll( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfChampionshipCategoriesMngrDlg( wxWindow* parent );
};

#endif // __udfChampionshipCategoriesMngrDlg__
