#ifndef __udfCsInfo__
#define __udfCsInfo__

/**
@file
Subclass of CsInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

class udfMainFrameBase;

/** Implementing CsInfo */
class udfCsInfo : public CsInfo
{
protected:
	// Handlers for CsInfo events.
	void OnRemoveChampionship( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnCategoryMngr( wxCommandEvent& event );
	void OnJudgeMngr( wxCommandEvent& event );
	void OnSendInvitation( wxCommandEvent& event );
	void OnDancersTeams( wxCommandEvent& event );
	void OnStartNumberAssign( wxCommandEvent& event );
	void OnAddBlock( wxCommandEvent& event );
	void OnTourEdit( wxCommandEvent& event );
	void OnRemoveTour( wxCommandEvent& event );
	void OnJudgesMark( wxCommandEvent& event );
	void OnCsTourReport( wxCommandEvent& event );

public:
	/** Constructor */
	udfCsInfo( wxWindow* parent);
//// end generated class members

private:
	CDbConnection*			m_pCon;
	udfMainFrameBase*		m_pMainWindow;
	wxTreeCtrl*				m_pTree;
	wxTreeItemId			m_parentItem;
	wxTreeItemId			m_itemId;

public:
	bool			Show(bool show = true);
	void			SetMainWindow(udfMainFrameBase* pMain) {m_pMainWindow = pMain;};
	void			SetCsTreeItem(wxTreeCtrl* pTree, wxTreeItemId& parentItem, wxTreeItemId& itemId) {m_pTree = pTree; m_parentItem = parentItem; m_itemId = itemId;};

	void			RefreshCities();
	void			RefreshTypes();

protected:
	int				GetSelectedCity();
	int				GetSelectedType();

	bool			ValidateValues();

};

#endif // __udfCsInfo__
