#ifndef __udfCategoryInfo__
#define __udfCategoryInfo__

/**
@file
Subclass of CategoryInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

class udfMainFrameBase;

/** Implementing CategoryInfo */
class udfCategoryInfo : public CategoryInfo
{
public:
	/** Constructor */
	udfCategoryInfo( wxWindow* parent );
//// end generated class members

private:
	CDbConnection*			m_pCon;
	udfMainFrameBase*		m_pMainWindow;
	wxTreeCtrl*				m_pTree;
	wxTreeItemId*			m_pParentItem;
	wxTreeItemId*			m_pTreeItemId;
	
public:
	bool			Show(bool show = true);
	void			SetMainWindow(udfMainFrameBase* pMain) {m_pMainWindow = pMain;};
	void			SetCsTreeItem(wxTreeCtrl* pTree, wxTreeItemId* pParentItem, wxTreeItemId* pItemId) {m_pTree = pTree; m_pParentItem = pParentItem; m_pTreeItemId = pItemId;};

};

#endif // __udfCategoryInfo__
