#ifndef __udfCodeDialog__
#define __udfCodeDialog__

/**
@file
Subclass of CodeDialog, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "map"

/** Implementing CodeDialog */
class udfCodeDialog : public CodeDialog
{
public:
	struct tDATA{
		wxString		name;
		long			code;
	};
	
	typedef std::map<unsigned int, tDATAt> tListMap;
	typedef std::map<unsigned int, tDATAt>::iterator tListIt;

private:
	tListMap	m_listMap;
	
protected:
	// Handlers for CodeDialog events.
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCodeDialog( wxWindow* parent );
	
public:

	unsigned int	AddListItem(unsigned int nId, wxString name, long code);
	
};

#endif // __udfCodeDialog__
