#ifndef __udfChampionshipJudgesTeamMngrDlg__
#define __udfChampionshipJudgesTeamMngrDlg__

/**
@file
Subclass of ChampionshipJudgesTeamMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "db.h"
#include "cdbmanager.h"
/** Implementing ChampionshipJudgesTeamMngrDlg */
class udfChampionshipJudgesTeamMngrDlg : public ChampionshipJudgesTeamMngrDlg
{
private:
	unsigned int 								m_nCSId;
	CDbConnection*								m_pCon;
	CChampionshipJudgesTeamTable::tTableMap		m_ChampionshipsJudges;
	CJudgesTable::tTableMap						m_Judges;
	
protected:
	// Handlers for ChampionshipJudgesTeamMngrDlg events.
	void OnAddAll( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnRemoveAll( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfChampionshipJudgesTeamMngrDlg( wxWindow* parent, unsigned int nId  );
	
protected:
	void 	RefreshAllList();
	void 	RefreshSelectedList();
};

#endif // __udfChampionshipJudgesTeamMngrDlg__
