#ifndef __udfCsTours__
#define __udfCsTours__

/**
@file
Subclass of CsTours, which is generated by wxFormBuilder.
*/

#include "udf.h"

//#include "tchampionshiptours.h"
#include "cdbmanager.h"

/** Implementing CsTours */
class udfCsTours : public CsTours
{
private:
	unsigned int		m_nCsId;
	CDbConnection*		m_pCon;
	
protected:
	// Handlers for CsTours events.
	void OnSelectTour( wxCommandEvent& event );
	void OnAddTour( wxCommandEvent& event );
	void OnRemoveTour( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCsTours( wxWindow* parent, unsigned int nCsId );
};

#endif // __udfCsTours__
