#ifndef __udfClubsMngrDlg__
#define __udfClubsMngrDlg__

/**
@file
Subclass of ClubsMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing ClubsMngrDlg */
class udfClubsMngrDlg : public ClubsMngrDlg
{
protected:
	// Handlers for ClubsMngrDlg events.
	void OnAddClub( wxCommandEvent& event );
	void OnRemoveClub( wxCommandEvent& event );
	void OnAccountInfo( wxCommandEvent& event );
	void OnDirectorInfo( wxCommandEvent& event );
	void OnTrainersMngr( wxCommandEvent& event );
	void OnDancersMngr( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnSelectClub( wxCommandEvent& event );
	void OnSearch( wxCommandEvent& event );
	void OnUpdate( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfClubsMngrDlg( wxWindow* parent );
<<<<<<< HEAD
=======
	
public:
	void	RefreshList();
	void	RefreshCities();
	void	RefreshCountries();
	int		GetSelectedCity();
	bool	ValidateData();
	bool	GetSelectedItemData(CClubsTable::tDATA*& pData);
	
>>>>>>> 3cca194... Manage Clubs functional has been implemented
};

#endif // __udfClubsMngrDlg__
