#ifndef __udfChampionshipJudgesTeamMngrDlg__
#define __udfChampionshipJudgesTeamMngrDlg__

/**
@file
Subclass of ChampionshipJudgesTeamMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing ChampionshipJudgesTeamMngrDlg */
class udfChampionshipJudgesTeamMngrDlg : public ChampionshipJudgesTeamMngrDlg
{
protected:
	// Handlers for ChampionshipJudgesTeamMngrDlg events.
	void OnAddAll( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnRemoveAll( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfChampionshipJudgesTeamMngrDlg( wxWindow* parent );
};

#endif // __udfChampionshipJudgesTeamMngrDlg__
