#ifndef __udfCategoriesMngrDlg__
#define __udfCategoriesMngrDlg__

/**
@file
Subclass of CategoriesMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing CategoriesMngrDlg */
class udfCategoriesMngrDlg : public CategoriesMngrDlg
{
protected:
	// Handlers for CategoriesMngrDlg events.
	void OnCategorySelected( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCategoriesMngrDlg( wxWindow* parent );
};

#endif // __udfCategoriesMngrDlg__
