#ifndef __udfCsTours__
#define __udfCsTours__

/**
@file
Subclass of CsTours, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "ttourtypes.h"
#include "cdbmanager.h"

/** Implementing CsTours */
class udfCsTours : public CsTours
{
protected:
	CDbConnection*						m_pCon;
	CTourTypesTable::tTableMap			m_types;
	
protected:
	// Handlers for CsTours events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
protected:
	void	RefreshTypes();
	
public:
	/** Constructor */
	udfCsTours( wxWindow* parent, unsigned int id, int limit);
	
	unsigned int	GetTypeId();
	int				GetLimit();
	bool	 		GetIsFinal(){ return m_checkFinal->GetValue();}
};

#endif // __udfCsTours__
