#ifndef __udfChampionshipTypeMngr__
#define __udfChampionshipTypeMngr__

/**
@file
Subclass of ChampionshipTypeMngr, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tchampionshiptype.h"
#include "cdbmanager.h"

/** Implementing ChampionshipTypeMngr */
class udfChampionshipTypeMngr : public ChampionshipTypeMngr
{
	CDbConnection*						m_pCon;
	CChampionshipTypeTable::tTableMap	m_Types;
	
protected:
	// Handlers for ChampionshipTypeMngr events.
	void OnSearch( wxCommandEvent& event );
	void OnSelectItem( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnUpdateCode( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfChampionshipTypeMngr( wxWindow* parent );
};

#endif // __udfChampionshipTypeMngr__
