#ifndef __udfCategoryInfo__
#define __udfCategoryInfo__

/**
@file
Subclass of CategoryInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

class udfMainFrameBase;

/** Implementing CategoryInfo */
class udfCategoryInfo : public CategoryInfo
{
public:
	/** Constructor */
	udfCategoryInfo( wxWindow* parent );
//// end generated class members

private:
	CDbConnection*			m_pCon;
	udfMainFrameBase*		m_pMainWindow;
	wxTreeCtrl*				m_pTree;
	wxTreeItemId			m_parentItem;
	wxTreeItemId			m_itemId;

public:
	bool			Show(bool show = true);
	void			SetMainWindow(udfMainFrameBase* pMain) {m_pMainWindow = pMain;};
	void			SetCsTreeItem(wxTreeCtrl* pTree, wxTreeItemId& parentItem, wxTreeItemId& itemId) {m_pTree = pTree; m_parentItem = parentItem; m_itemId = itemId;};

};

#endif // __udfCategoryInfo__
