#ifndef __udfCategoriesMngrDlg__
#define __udfCategoriesMngrDlg__

/**
@file
Subclass of CategoriesMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tliga.h"
#include "tagecategory.h"
#include "tdancetypes.h"
#include "tcategories.h"
#include "cdbmanager.h"

/** Implementing CategoriesMngrDlg */
class udfCategoriesMngrDlg : public CategoriesMngrDlg
{
private:
	CDbConnection* m_pCon;
	
	CCategoriesTable::tTableMap m_Categories;
	
	CLigaTable::tTableMap m_Ligues;
	CAgeCategoryTable::tTableMap m_AgeCats;
	CDanceTypesTable::tTableMap m_DanceTypes;
protected:
	// Handlers for CategoriesMngrDlg events.
	void OnCategorySelected( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnUpdate( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnCategorySearch( wxCommandEvent& event );
	void OnAgeChanged( wxCommandEvent& event );
	void OnLigaChanged( wxCommandEvent& event );
	void OnDanceChanged( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCategoriesMngrDlg( wxWindow* parent );

protected:
	void 	RefreshData();
	void 	RefreshAgeCategories();
	void 	RefreshDanceTypes();
	void 	RefreshLigues();
	
	int 	GetSelectedDanceType();
	int 	GetSelectedLigue();
	int 	GetSelectedAgeCat();
	
	void	ResetCategoryName();
};

#endif // __udfCategoriesMngrDlg__
