#ifndef __udfCsTourReport__
#define __udfCsTourReport__

/**
@file
Subclass of CsTourReport, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "map"

typedef std::map<unsigned long, int> tMarks;
typedef std::map<unsigned long, int>::iterator tMarksIt;
typedef std::map<unsigned long, int>::const_iterator tMarksItC;

typedef std::map<unsigned long, wxString> tJudges;
typedef std::map<unsigned long, wxString>::iterator tJudgesIt;
typedef std::map<unsigned long, wxString>::const_iterator tJudgesItC;

typedef std::map<unsigned long, tMarks> tDancerMarks;
typedef std::map<unsigned long, tMarks>::iterator tDancerMarksIt;
typedef std::map<unsigned long, tMarks>::const_iterator tDancerMarksItC;

/** Implementing CsTourReport */
class udfCsTourReport : public CsTourReport
{
private:
	const tDancerMarks&			m_dancerMarks;
	const tJudges&				m_judgesMap;
	int							m_nLimit;
	unsigned long				m_nTourId;
	wxArrayString				m_report;
	
protected:
	// Handlers for CsTourReport events.
	void OnReport( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnTeamSelect( wxListEvent& event );
	void OnBeginDrag( wxListEvent& event );
	
public:
	/** Constructor */
	udfCsTourReport( wxWindow* parent, unsigned long nTourId, int limit, const tJudges& judgesMap, const tDancerMarks& dancerMarks );
	
protected:
	void		CreateHeaders();
	void		FillList();
	
	void		FormatReportTableHeader();
	void		FormatReportTableBody();
};

#endif // __udfCsTourReport__
