#ifndef __udfDancersTeamMngr__
#define __udfDancersTeamMngr__

/**
@file
Subclass of DancersTeamMngr, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing DancersTeamMngr */
class udfDancersTeamMngr : public DancersTeamMngr
{
protected:
	// Handlers for DancersTeamMngr events.
	void OnAddDancerTeam( wxCommandEvent& event );
	void OnRemoveTancerTeam( wxCommandEvent& event );
	void OnAddDancerTeamCategory( wxCommandEvent& event );
	void OnRemoveDancerTeamCategory( wxCommandEvent& event );
	void OnAddDancerTeamDancer( wxCommandEvent& event );
	void OnRemoveDancerTeamDancer( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfDancersTeamMngr( wxWindow* parent );
};

#endif // __udfDancersTeamMngr__
