#ifndef __udfFinalMarks__
#define __udfFinalMarks__

/**
@file
Subclass of FinalMarks, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

/** Implementing FinalMarks */
class udfFinalMarks : public FinalMarks
{
protected:
	typedef std::map<int, unsigned int>				tI2UiMap;
	typedef std::map<unsigned int, int>				tUi2IMap;

private:
	CDbConnection*				m_pCon;
	unsigned int 				m_tourId;
	unsigned int 				m_catId;

	tUi2IMap					m_id2row;
	tI2UiMap					m_row2id;
	tUi2IMap					m_id2col;
	tI2UiMap					m_col2id;

protected:
	// Handlers for FinalMarks events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnCellLClick( wxGridEvent& event );
	void OnKeyUp( wxKeyEvent& event );
	void OnKeyDown( wxKeyEvent& event );

public:
	/** Constructor */
	udfFinalMarks( wxWindow* parent, unsigned int tourId );
//// end generated class members
	
	bool				Validate();
	void				RefreshGrid();
	void				UpdateMarks();
};

#endif // __udfFinalMarks__
