#ifndef __udfJudgesMngr__
#define __udfJudgesMngr__

/**
@file
Subclass of JudgesMngr, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing JudgesMngr */
class udfJudgesMngr : public JudgesMngr
{
protected:
	// Handlers for JudgesMngr events.
	void OnAddJudge( wxCommandEvent& event );
	void OnRemoveJudge( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfJudgesMngr( wxWindow* parent );
};

#endif // __udfJudgesMngr__
