#ifndef __udfJudgeMark__
#define __udfJudgeMark__

/**
@file
Subclass of JudgeMark, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing JudgeMark */
class udfJudgeMark : public JudgeMark
{
protected:
	// Handlers for JudgeMark events.
	void OnSelectJudge( wxCommandEvent& event );
	void OnSelectTeam( wxCommandEvent& event );
	void OnShowAll( wxCommandEvent& event );
	void OnSearch( wxCommandEvent& event );
	void OnPlus( wxCommandEvent& event );
	void OnMinus( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfJudgeMark( wxWindow* parent );
};

#endif // __udfJudgeMark__
