#ifndef __udfJudgeMark__
#define __udfJudgeMark__

/**
@file
Subclass of JudgeMark, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

/** Implementing JudgeMark */
class udfJudgeMark : public JudgeMark
{
protected:
	typedef std::map<int, unsigned int>				tI2UiMap;
	typedef std::map<unsigned int, int>				tUi2IMap;

private:
	CDbConnection*				m_pCon;
	unsigned int 				m_tourId;
	unsigned int 				m_catId;

	tUi2IMap					m_id2row;
	tI2UiMap					m_row2id;
	tUi2IMap					m_id2col;
	tI2UiMap					m_col2id;
	
	unsigned int 				m_row;
	unsigned int 				m_col;
	

protected:
	// Handlers for JudgeMark events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnCellLClick( wxGridEvent& event );
	void OnKeyUp( wxKeyEvent& event );
	void OnCellChange(wxGridEvent& event);
	void OnSearch( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfJudgeMark( wxWindow* parent, unsigned int tourId );
	//// end generated class members

	void				RefreshGrid();
	void				UpdateMarks();
};

#endif // __udfJudgeMark__
