#ifndef __udfJudgeCategories__
#define __udfJudgeCategories__

/**
@file
Subclass of JudgeCategories, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "db.h"
#include "cdbmanager.h"
//// end generated include

/** Implementing JudgeCategories */
class udfJudgeCategories : public JudgeCategories
{
private:
	unsigned int								m_nId;
	CDbConnection*								m_pCon;
	CCategoriesTable::tTableMap					m_cats;
	CJudgesCategoriesHaveTable::tTableMap		m_catsHave;
	
protected:
	// Handlers for JudgeCategories events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnSetAll( wxCommandEvent& event );
	void OnClearAll( wxCommandEvent& event );

public:
	/** Constructor */
	udfJudgeCategories( wxWindow* parent, unsigned int nId );
//// end generated class members

protected:
	void	RefreshList();

};

#endif // __udfJudgeCategories__
