#ifndef __udfMainFrameBase__
#define __udfMainFrameBase__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "db.h"
#include "cdbmanager.h"

class udfCsInfo;
class udfBlockInfo;
class udfCategoryInfo;
class udfTourInfo;

typedef enum{
	IT_CS = 0,
	IT_BLOCK,
	IT_CAT,
	IT_TOUR,
}eITEM_TYPE;

class udfTreeItemData : public wxTreeItemData
{
public:
    udfTreeItemData(const unsigned long nId, eITEM_TYPE type) : m_nId(nId), m_type(type) { }

    void 			ShowInfo(wxTreeCtrl *tree);
    const wxChar*	GetDesc() const { return wxString::Format("%ld", m_nId).c_str(); }
	unsigned long	GetId() const {return m_nId; }
	eITEM_TYPE		GetType()const {return m_type; }

private:
	eITEM_TYPE		m_type;
    unsigned long 	m_nId;
};

/** Implementing MainFrameBase */
class udfMainFrameBase : public MainFrameBase
{
protected:
	// Handlers for MainFrameBase events.
	void OnCloseFrame( wxCloseEvent& event );
	void OnExitClick( wxCommandEvent& event );

	void OnMenuCategoryManage( wxCommandEvent& event );
	void OnMenuClubManage( wxCommandEvent& event );
	void OnMenuJudgeManage( wxCommandEvent& event );
	void OnMenuChampionshipTypes( wxCommandEvent& event );
	void OnMenuOptions( wxCommandEvent& event );
	void OnMenuStaff( wxCommandEvent& event );
	void OnMenuStaffRoles( wxCommandEvent& event );

	void OnAddChampionsip( wxCommandEvent& event );
	void OnStartNumberAssign( wxCommandEvent& event );
	void OnJudgeMngr( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnAboutDlg( wxCommandEvent& event );
	void OnDancersTeams( wxCommandEvent& event );

	void OnDanceTypesCodeMgr( wxCommandEvent& event );
	void OnLigueCodeMgr( wxCommandEvent& event );
	void OnAgeCodesMgr( wxCommandEvent& event );

	void OnCountriesMngr( wxCommandEvent& event );
	void OnCitiesMngr( wxCommandEvent& event );

	void OnSearch( wxCommandEvent& event );
	void OnCsSelect(wxTreeEvent& event);

	void OnCsTourReport( wxCommandEvent& event );

	void CsSelected();
	void BlockSelected();
	void CatSelected();
	void TourSelected();


private:
	CDbConnection*						m_pCon;
	CChampionshipTable::tTableMap		m_Championships;
	CCountriesTable::tTableMap			m_Countries;
	CCitiesTable::tTableMap				m_Cities;
	CChampionshipTypeTable::tTableMap 	m_ChampionshipTypes;

	wxTreeItemId						m_root;

	udfCsInfo*							m_pageCsInfo;
	udfBlockInfo*						m_pageBlockInfo;
	udfCategoryInfo*					m_pageCatInfo;
	udfTourInfo*						m_pageTourInfo;

protected:

	wxDateTime		GetChDateById(unsigned int nId);

	wxTreeItemId	GetItemByType(eITEM_TYPE type);

	bool			IsFinalTourAdded();

public:
	/** Constructor */
	udfMainFrameBase( wxWindow* parent );
	virtual ~udfMainFrameBase();

public:
	int				ShowDanceTypesMngrDlg();
	int				ShowLiguesMngrDlg();
	int				ShowAgeCatsMngrDlg();
	int				ShowCsCategoryManager();
	int				ShowCsJudgesManager();

	wxTreeItemId	GetSelectedCs();
	wxTreeItemId	GetSelectedCsBlock();
	wxTreeItemId	GetSelectedBlockCategory();
	wxTreeItemId	GetSelectedCatTour();

	void			RefreshList();
	void			RefreshCs(unsigned int id, wxTreeItemId parent);
	void			RefreshCsBlock(unsigned int id, wxTreeItemId parent);
	void			RefreshCategory(unsigned int id, wxTreeItemId parent);

	void 			OnAddBlock( wxCommandEvent& event );
	void 			OnAddTour( wxCommandEvent& event );

	void			ShowStartNumberAssign();

};

#endif // __udfMainFrameBase__
