#ifndef __udfMainFrameBase__
#define __udfMainFrameBase__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tchampionship.h"
#include "tcountries.h"
#include "tcities.h"
#include "tchampionshiptype.h"
#include "cdbmanager.h"

/** Implementing MainFrameBase */
class udfMainFrameBase : public MainFrameBase
{
protected:
	// Handlers for MainFrameBase events.
	void OnCloseFrame( wxCloseEvent& event );
	void OnExitClick( wxCommandEvent& event );
	void OnMenuCategoryManage( wxCommandEvent& event );
	void OnMenuClubManage( wxCommandEvent& event );
	void OnMenuJudgeManage( wxCommandEvent& event );
	void OnMenuChampionshipTypes( wxCommandEvent& event );
	void OnAddChampionsip( wxCommandEvent& event );
	void OnRemoveChampionship( wxCommandEvent& event );
	void OnCategoryMngr( wxCommandEvent& event );
	void OnStartNumberAssign( wxCommandEvent& event );
	void OnJudgeMngr( wxCommandEvent& event );
	void OnSendInvitation( wxCommandEvent& event );
	void OnResults( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnAboutDlg( wxCommandEvent& event );
	void OnDancersTeams( wxCommandEvent& event );
	
	void OnDanceTypesCodeMgr( wxCommandEvent& event );
	void OnLigueCodeMgr( wxCommandEvent& event );
	void OnAgeCodesMgr( wxCommandEvent& event );
	
	void OnCountriesMngr( wxCommandEvent& event );
	void OnCitiesMngr( wxCommandEvent& event );
	
	void OnSearch( wxCommandEvent& event );
	void OnSelectChampionship( wxCommandEvent& event );

private:
	CDbConnection*						m_pCon;
	CChampionshipTable::tTableMap		m_Championships;
	CCountriesTable::tTableMap			m_Countries;
	CCitiesTable::tTableMap				m_Cities;
	CChampionshipTypeTable::tTableMap 	m_ChampionshipTypes;

protected:
	void		RefreshList();
	void		RefreshCities();
	void		RefreshCountries();
	void		RefreshTypes();
	int			GetSelectedCity();
	int			GetSelectedType();
	
	bool		ValidateValues();
	
	wxDateTime	GetChDateById(unsigned int nId);

public:
	/** Constructor */
	udfMainFrameBase( wxWindow* parent );
	
public:
	int ShowDanceTypesMngrDlg();
	int ShowLiguesMngrDlg();
	int ShowAgeCatsMngrDlg();

};

#endif // __udfMainFrameBase__
