#ifndef __udfPaymentHistory__
#define __udfPaymentHistory__

/**
@file
Subclass of PaymentHistory, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "cdbmanager.h"
#include "tpaymenthistory.h"

//// end generated include

/** Implementing PaymentHistory */
class udfPaymentHistory : public PaymentHistory
{
protected:
	char								m_cType;
	unsigned long						m_nPersonId;
	CDbConnection*						m_pCon;
	CPaymentHistoryTable::tTableMap		m_payments;
	
protected:
	// Handlers for PaymentHistory events.
	void OnAdd( wxCommandEvent& event );
	void OnUpdate( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
public:
	/** Constructor */
	udfPaymentHistory( wxWindow* parent, unsigned long nId, char cType );
//// end generated class members

protected:
	void RefreshList();
	void RefreshHeaders();
	
};

#endif // __udfPaymentHistory__
