#ifndef __udfPayment__
#define __udfPayment__

/**
@file
Subclass of Payment, which is generated by wxFormBuilder.
*/

#include "udf.h"

//// end generated include

/** Implementing Payment */
class udfPayment : public Payment
{
	protected:
		// Handlers for Payment events.
		void OnSave( wxCommandEvent& event );
		void OnDiscard( wxCommandEvent& event );
	public:
		/** Constructor */
		udfPayment( wxWindow* parent );
	//// end generated class members
	
};

#endif // __udfPayment__
