#ifndef __udfSettings__
#define __udfSettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "udf.h"

//// end generated include

/** Implementing Settings */
class udfSettings : public Settings
{
	protected:
		// Handlers for Settings events.
		void OnSave( wxCommandEvent& event );
		void OnDiscard( wxCommandEvent& event );
	public:
		/** Constructor */
		udfSettings( wxWindow* parent );
	//// end generated class members
	
};

#endif // __udfSettings__
