#ifndef __udfStartNumberAssignDlg__
#define __udfStartNumberAssignDlg__

/**
@file
Subclass of StartNumberAssignDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tchampionshipteam.h"
#include "cdbmanager.h"

/** Implementing StartNumberAssignDlg */
class udfStartNumberAssignDlg : public StartNumberAssignDlg
{
private:
	unsigned int 								m_nCsId;
	CDbConnection*								m_pCon;
	CChampionshipTeamsTable* 					m_pTable;
	CChampionshipTeamsTable::tDATA 				m_Filter;
	CChampionshipTeamsTable::tTableMap			m_CsTeams;
	unsigned int								m_nLastAssign;
	
protected:
	// Handlers for StartNumberAssignDlg events.
	void OnSearch( wxCommandEvent& event );
	void OnRandomFind( wxCommandEvent& event );
	void OnNextFind( wxCommandEvent& event );
	void OnAssign( wxCommandEvent& event );
	void OnSelectTeam( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfStartNumberAssignDlg( wxWindow* parent, unsigned int nCsId );
	
protected:
	void	RefreshList();
};

#endif // __udfStartNumberAssignDlg__
