#ifndef __udfTourInfo__
#define __udfTourInfo__

/**
@file
Subclass of TourInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

class udfMainFrameBase;

/** Implementing TourInfo */
class udfTourInfo : public TourInfo
{
public:
	/** Constructor */
	udfTourInfo( wxWindow* parent );
//// end generated class members

private:
	CDbConnection*			m_pCon;
	udfMainFrameBase*		m_pMainWindow;
	wxTreeCtrl*				m_pTree;
	wxTreeItemId*			m_pParentItem;
	wxTreeItemId*			m_pTreeItemId;
	
public:
	bool			Show(bool show = true);
	void			SetMainWindow(udfMainFrameBase* pMain) {m_pMainWindow = pMain;};
	void			SetCsTreeItem(wxTreeCtrl* pTree, wxTreeItemId* pParentItem, wxTreeItemId* pItemId) {m_pTree = pTree; m_pParentItem = pParentItem; m_pTreeItemId = pItemId;};

};

#endif // __udfTourInfo__
