#ifndef __udfTeamCategoryMngrDlg__
#define __udfTeamCategoryMngrDlg__

/**
@file
Subclass of TeamCategoryMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing TeamCategoryMngrDlg */
class udfTeamCategoryMngrDlg : public TeamCategoryMngrDlg
{
protected:
	// Handlers for TeamCategoryMngrDlg events.
	void OnAddAll( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnRemoveAll( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfTeamCategoryMngrDlg( wxWindow* parent );
};

#endif // __udfTeamCategoryMngrDlg__
