#ifndef __udfTrainersMngrDlg__
#define __udfTrainersMngrDlg__

/**
@file
Subclass of TarinersMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "ttreiners.h"
#include "tclubs.h"

#include "cdbmanager.h"

/** Implementing TarinersMngrDlg */
class udfTrainersMngrDlg : public TrainersMngrDlg
{
private:
	unsigned int					m_nClubId;
	CDbConnection*					m_pCon;
	CClubsTable::tTableMap			m_Clubs;
	CTrainersTable::tTableMap		m_Trainers;
	
protected:
	// Handlers for TarinersMngrDlg events.
	void OnAddTrainer( wxCommandEvent& event );
	void OnRemoveTrainer( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnSearch( wxCommandEvent& event );
	void OnSelectTrainer( wxCommandEvent& event );
	void OnUpdate( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfTrainersMngrDlg( wxWindow* parent, unsigned int nClubId );
	
private:
	int 		GetSelectedClub();
	void		RefreshList();
	void		RefreshClubs();
	bool		ValidateData();
	bool		GetSelectedItemData(CTrainersTable::tDATA*& pData);

public:
	bool		GetNameById(unsigned int id, wxString& name);	
	
};

#endif // __udfTrainersMngrDlg__
