#ifndef __udfTeamDancersMngrDlg__
#define __udfTeamDancersMngrDlg__

/**
@file
Subclass of TeamDancersMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing TeamDancersMngrDlg */
class udfTeamDancersMngrDlg : public TeamDancersMngrDlg
{
protected:
	// Handlers for TeamDancersMngrDlg events.
	void OnAddAll( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnRemoveAll( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfTeamDancersMngrDlg( wxWindow* parent );
};

#endif // __udfTeamDancersMngrDlg__
