#ifndef __udfTarinersMngrDlg__
#define __udfTarinersMngrDlg__

/**
@file
Subclass of TarinersMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing TarinersMngrDlg */
class udfTarinersMngrDlg : public TarinersMngrDlg
{
protected:
	// Handlers for TarinersMngrDlg events.
	void OnAddTrainer( wxCommandEvent& event );
	void OnRemoveTrainer( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfTarinersMngrDlg( wxWindow* parent );
};

#endif // __udfTarinersMngrDlg__
