#ifndef __udfAccountInfo__
#define __udfAccountInfo__

/**
@file
Subclass of AccountInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing AccountInfo */
class udfAccountInfo : public AccountInfo
{
protected:
	// Handlers for AccountInfo events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnShowPass( wxCommandEvent& event );

public:
	/** Constructor */
	udfAccountInfo( wxWindow* parent );
	
public:
	wxString	GetLogin();
	void		SetLogin(wxString login);
	wxString	GetPass();
	void		SetPass(wxString pass);
};

#endif // __udfAccountInfo__
