#ifndef __udfCitiesMngr__
#define __udfCitiesMngr__

/**
@file
Subclass of CitiesMngr, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tcountries.h"
#include "tcities.h"
#include "cdbmanager.h"

/** Implementing CitiesMngr */
class udfCitiesMngr : public CitiesMngr
{
	CDbConnection* m_pCon;
	CCitiesTable::tTableMap m_Cities;
	CCountriesTable::tTableMap m_Countries;

protected:
	// Handlers for CitiesMngr events.
	void OnSearch( wxCommandEvent& event );
	void OnSelectItem( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnUpdateCode( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );

protected:
	int GetSelectedCountry();
	
public:
	/** Constructor */
	udfCitiesMngr( wxWindow* parent );
	void RefreshCountries();
};

#endif // __udfCitiesMngr__
