#ifndef __udfCodeDialog__
#define __udfCodeDialog__

/**
@file
Subclass of CodeDialog, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "map"

/** Implementing CodeDialog */
class udfCodeDialog : public CodeDialog
{
public:
	struct tDATA{
		unsigned int	nId;
		wxString		name;
		long			code;
	};
	
	typedef std::map<unsigned int, tDATA> tListMap;
	typedef std::map<unsigned int, tDATA>::iterator tListIt;

private:
	tListMap	m_listMap;
	
protected:
	// Handlers for CodeDialog events.
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnSelectItem( wxCommandEvent& event );
	void OnUpdateCode( wxCommandEvent& event );
	void OnSearch( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCodeDialog( wxWindow* parent );
	
public:
	void		RefreshList();
	void 		SetListName(wxString listName);
	void		AddListItem(unsigned int nId, wxString name, long code);
	tListMap	GetResultList();
};

#endif // __udfCodeDialog__
