#ifndef __udfCountriesMngr__
#define __udfCountriesMngr__

/**
@file
Subclass of CountriesMngr, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tcountries.h"
#include "cdbmanager.h"

/** Implementing CountriesMngr */
class udfCountriesMngr : public CountriesMngr
{
	CDbConnection*				m_pCon;
	CCountriesTable::tTableMap	m_Countries;
	
protected:
	// Handlers for CountriesMngr events.
	void OnSearch( wxCommandEvent& event );
	void OnSelectItem( wxCommandEvent& event );
	void OnAdd( wxCommandEvent& event );
	void OnRemove( wxCommandEvent& event );
	void OnUpdateCode( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfCountriesMngr( wxWindow* parent );
};

#endif // __udfCountriesMngr__
