#ifndef __udfDirectorInfo__
#define __udfDirectorInfo__

/**
@file
Subclass of DirectorInfo, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing DirectorInfo */
class udfDirectorInfo : public DirectorInfo
{
protected:
	// Handlers for DirectorInfo events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfDirectorInfo( wxWindow* parent );
public:
	void		SetName(wxString value);
	void		SetBd(time_t date);
	void		SetEmail(wxString value);
	void		SetPhone(wxString value);
	wxString	GetName();
	time_t		GetBd();
	wxString	GetEmail();
	wxString	GetPhone();
};

#endif // __udfDirectorInfo__
