#ifndef __udfLoginDlg__
#define __udfLoginDlg__

/**
@file
Subclass of LoginDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

//// end generated include

/** Implementing LoginDlg */
class udfLoginDlg : public LoginDlg
{
	protected:
		// Handlers for LoginDlg events.
		void OnOk( wxCommandEvent& event );
		void OnCancel( wxCommandEvent& event );
	public:
		/** Constructor */
		udfLoginDlg( wxWindow* parent );
	//// end generated class members
	
};

#endif // __udfLoginDlg__
