#ifndef __udfReportPreview__
#define __udfReportPreview__

/**
@file
Subclass of ReportPreview, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing ReportPreview */
class udfReportPreview : public ReportPreview
{
	const wxArrayString& m_data;
protected:
	// Handlers for ReportPreview events.
	void OnPrint( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfReportPreview( wxWindow* parent, const wxArrayString& data );
};

#endif // __udfReportPreview__
