#ifndef __udfStartNumberAssignDlg__
#define __udfStartNumberAssignDlg__

/**
@file
Subclass of StartNumberAssignDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

#include "tchampionshipteam.h"
#include "cdbmanager.h"

/** Implementing StartNumberAssignDlg */
class udfStartNumberAssignDlg : public StartNumberAssignDlg
{
typedef map<unsigned int, unsigned int>				tUi2Ui;
typedef map<unsigned int, unsigned int>::iterator	tUi2UiIt;

private:
	unsigned int 								m_nCsId;
	CDbConnection*								m_pCon;
	CChampionshipTeamsTable::tTableMap			m_CsTeams;
	tUi2Ui										m_StNumMap;

protected:
	// Handlers for StartNumberAssignDlg events.
	void OnSearch( wxCommandEvent& event );
	void OnFindRandom( wxCommandEvent& event );
	void OnFindNext( wxCommandEvent& event );
	void OnAllAssignRandom( wxCommandEvent& event );
	void OnAllAssignIncrease( wxCommandEvent& event );
	void OnAssign( wxCommandEvent& event );
	void OnSelectTeam( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );

public:
	/** Constructor */
	udfStartNumberAssignDlg( wxWindow* parent, unsigned int nCsId );

protected:
	void			RefreshList();

};

#endif // __udfStartNumberAssignDlg__
