#ifndef __udfStaff__
#define __udfStaff__

/**
@file
Subclass of Staff, which is generated by wxFormBuilder.
*/

#include "udf.h"
#include "cdbmanager.h"

//// end generated include

/** Implementing Staff */
class udfStaff : public Staff
{
	protected:
		CDbConnection*			m_pCon;

	protected:
		// Handlers for Staff events.
		void OnAdd( wxCommandEvent& event );
		void OnUpdate( wxCommandEvent& event );
		void OnRemove( wxCommandEvent& event );
		void OnSave( wxCommandEvent& event );
		void OnDiscard( wxCommandEvent& event );
		void OnSelectWorker( wxCommandEvent& event );

	public:
		/** Constructor */
		udfStaff( wxWindow* parent );
	//// end generated class members

};

#endif // __udfStaff__
