#ifndef __udfSettings__
#define __udfSettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "wx/config.h"

#include "udf.h"
#include "db.h"
#include "cdbmanager.h"

//// end generated include

/** Implementing Settings */
class udfSettings : public Settings
{
private:
	CDbConnection*				m_pCon;
	CTourTypesTable::tTableMap	m_tourTypeInfo;

protected:
	// Handlers for Settings events.
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	void OnTest( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfSettings( wxWindow* parent );
	virtual ~udfSettings();
//// end generated class members

protected:
	void	Refresh();

};

#endif // __udfSettings__
