#ifndef __udfDancersMngrDlg__
#define __udfDancersMngrDlg__

/**
@file
Subclass of DancersMngrDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing DancersMngrDlg */
class udfDancersMngrDlg : public DancersMngrDlg
{
protected:
	// Handlers for DancersMngrDlg events.
	void OnAddDancer( wxCommandEvent& event );
	void OnRemoveDancer( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfDancersMngrDlg( wxWindow* parent );
};

#endif // __udfDancersMngrDlg__
