#ifndef __udfStartNumberAssignDlg__
#define __udfStartNumberAssignDlg__

/**
@file
Subclass of StartNumberAssignDlg, which is generated by wxFormBuilder.
*/

#include "udf.h"

/** Implementing StartNumberAssignDlg */
class udfStartNumberAssignDlg : public StartNumberAssignDlg
{
protected:
	// Handlers for StartNumberAssignDlg events.
	void OnRandomFind( wxCommandEvent& event );
	void OnNextFind( wxCommandEvent& event );
	void OnAssign( wxCommandEvent& event );
	void OnSave( wxCommandEvent& event );
	void OnDiscard( wxCommandEvent& event );
	
public:
	/** Constructor */
	udfStartNumberAssignDlg( wxWindow* parent );
};

#endif // __udfStartNumberAssignDlg__
