#!/bin/bash

initId=101

## Create resource.cpp
id=$initId
ofile=resource.h
rm -f $ofile

header="// This file is autogenerated!
\n// To regenerate content, please, use 'convert_all.sh'
\n//"

echo -e $header>>$ofile
echo "">>$ofile
echo "#ifndef __RESOURCES_H__">>$ofile
echo "#define __RESOURCES_H__">>$ofile
echo "">>$ofile
echo "#include \"wx/artprov.h\"">>$ofile
echo "#include \"wx/bitmap.h\"">>$ofile
echo "">>$ofile

for pic in `ls *.png | awk -F. '{print $1}'`
do
	lpic=`echo $pic | awk -F_ '{print tolower($1)}'`
	upic=`echo $pic | awk -F_ '{print toupper($1)}'`

	echo "#define IDI_ICON_$upic	$id">>$ofile
	((id+=1))
done
echo "">>$ofile
echo "wxBitmap* GetResourceBmp(int id);">>$ofile
echo "">>$ofile
echo "#endif //__RESOURCES_H__">>$ofile

## Create resource.cpp
ofile=resource.cpp
id=$initId

rm -f $ofile

echo -e $header>>$ofile
echo "">>$ofile
echo "#include \"resource.h\"">>$ofile
echo "">>$ofile
for pic in `ls *.png | awk -F. '{print $1}'`
do
	lpic=`echo $pic | awk -F_ '{print tolower($1)}'`
	upic=`echo $pic | awk -F_ '{print toupper($1)}'`

	echo "$pic.png -> icon$lpic.xpm"
	convert $pic.png $lpic.xpm
	sed -i 's/'$lpic'/'$lpic'_xpm/g' $lpic.xpm
	echo "#include \"$lpic.xpm\"">>$ofile
	((id+=1))
done
echo "">>$ofile
echo "wxBitmap* GetResourceBmp(int id)">>$ofile
echo "{">>$ofile

for pic in `ls *.png | awk -F. '{print $1}'`
do
	lpic=`echo $pic | awk -F_ '{print tolower($1)}'`
	upic=`echo $pic | awk -F_ '{print toupper($1)}'`

	echo "    if(id == IDI_ICON_$upic)	return new wxBitmap($lpic_xpm);">>$ofile
done
	echo "">>$ofile
	echo "    return new wxBitmap();">>$ofile
echo "}">>$ofile
echo "">>$ofile


