#ifndef __UDFERRORCODES_H__
#define __UDFERRORCODES_H__

typedef enum
{
	UDF_OK = 0,
	UDF_UNKNOWN_ERROR,
	UDF_INTERNAL_ERROR,
	UDF_MYSQL_INTERNAL_ERROR,
	UDF_RUNTIME_ERROR,
	UDF_CRASH,
	
	UDF_FAIL = 100,
	UDF_NO_DRIVER_FOUND,
	UDF_NO_CONNECTION_OPENED,
	UDF_NO_STATEMENT,
	UDF_NO_CONNECTION,

	
} UDF_ERROR;

#endif //__UDFERRORCODES_H__